name: coverage
on: push

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Go test coverage
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go test -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v5
